### ISSUE TITLE
Add healthcare areas as visualisation layer

### ISSUE THREAD

**Issue by timlinux** [healthsites/healthsites#1405]
#Goal

To see the healthcare boundaries as a backdrop layer in HS.io.

# Tasks

- [ ] @nyakudyaa  Add healthcare boundaries to https://github.com/healthsites/healthsites/blob/develop/deployment/docker-osm-healthcare/mapping.yml
- [ ] @nyakudyaa Add a visualisation layer via the new geoserver instance we are setting up
![image](https://user-images.githubusercontent.com/178003/78543924-49f77800-77f1-11ea-8cbd-f6687d6397b0.png)
- [ ] @dimasciput Add a widget in the map page that lets you hide / show the healthcare boundaries
